topics:
  building_1_temperature: campus/building_1/temperature
  building_1_humidity: campus/building_1/humidity
  building_1_power: campus/building_1/power
  building_1_co2: campus/building_1/co2
  building_1_motion: campus/building_1/motion
  building_1_fire_alarm: campus/building_1/fire_alarm
  building_1_thermostat_setpoint: campus/building_1/thermostat_setpoint
  building_2_temperature: campus/building_2/temperature
  building_2_humidity: campus/building_2/humidity
  building_2_power: campus/building_2/power
  building_2_co2: campus/building_2/co2
  building_2_motion: campus/building_2/motion
  building_2_fire_alarm: campus/building_2/fire_alarm
  building_2_thermostat_setpoint: campus/building_2/thermostat_setpoint
  building_3_temperature: campus/building_3/temperature
  building_3_humidity: campus/building_3/humidity
  building_3_power: campus/building_3/power
  building_3_co2: campus/building_3/co2
  building_3_motion: campus/building_3/motion
  building_3_fire_alarm: campus/building_3/fire_alarm
  building_3_thermostat_setpoint: campus/building_3/thermostat_setpoint
  building_4_temperature: campus/building_4/temperature
  building_4_humidity: campus/building_4/humidity
  building_4_power: campus/building_4/power
  building_4_co2: campus/building_4/co2
  building_4_motion: campus/building_4/motion
  building_4_fire_alarm: campus/building_4/fire_alarm
  building_4_thermostat_setpoint: campus/building_4/thermostat_setpoint
  building_5_temperature: campus/building_5/temperature
  building_5_humidity: campus/building_5/humidity
  building_5_power: campus/building_5/power
  building_5_co2: campus/building_5/co2
  building_5_motion: campus/building_5/motion
  building_5_fire_alarm: campus/building_5/fire_alarm
  building_5_thermostat_setpoint: campus/building_5/thermostat_setpoint
  building_6_temperature: campus/building_6/temperature
  building_6_humidity: campus/building_6/humidity
  building_6_power: campus/building_6/power
  building_6_co2: campus/building_6/co2
  building_6_motion: campus/building_6/motion
  building_6_fire_alarm: campus/building_6/fire_alarm
  building_6_thermostat_setpoint: campus/building_6/thermostat_setpoint
  building_7_temperature: campus/building_7/temperature
  building_7_humidity: campus/building_7/humidity
  building_7_power: campus/building_7/power
  building_7_co2: campus/building_7/co2
  building_7_motion: campus/building_7/motion
  building_7_fire_alarm: campus/building_7/fire_alarm
  building_7_thermostat_setpoint: campus/building_7/thermostat_setpoint
  building_8_temperature: campus/building_8/temperature
  building_8_humidity: campus/building_8/humidity
  building_8_power: campus/building_8/power
  building_8_co2: campus/building_8/co2
  building_8_motion: campus/building_8/motion
  building_8_fire_alarm: campus/building_8/fire_alarm
  building_8_thermostat_setpoint: campus/building_8/thermostat_setpoint
  building_9_temperature: campus/building_9/temperature
  building_9_humidity: campus/building_9/humidity
  building_9_power: campus/building_9/power
  building_9_co2: campus/building_9/co2
  building_9_motion: campus/building_9/motion
  building_9_fire_alarm: campus/building_9/fire_alarm
  building_9_thermostat_setpoint: campus/building_9/thermostat_setpoint
  building_10_temperature: campus/building_10/temperature
  building_10_humidity: campus/building_10/humidity
  building_10_power: campus/building_10/power
  building_10_co2: campus/building_10/co2
  building_10_motion: campus/building_10/motion
  building_10_fire_alarm: campus/building_10/fire_alarm
  building_10_thermostat_setpoint: campus/building_10/thermostat_setpoint
